### PR TITLE
fix: #2103 and resource pot id hash conflicts

### LINKED ISSUE #2103: [Bug Report]:react+antd-mobile， After packaging and running the file build, a TypeError occurred: Cannot read properties of undefined (reading 'createElement')
### Steps to reproduce
**Local operation is normal**
Image

**Both the built-in browser of Android 8 and Google Chrome will encounter errors when running build**
Image

Image

**Below is the farm.config configuration**

Image

### Reproduce link

_No response_

### What is actually happening?

1.Yarn serves that all components related to antd mobile can be displayed normally
2.When the file built by yarn encounters the use of the Swiper component in antd mobile during runtime, the page will crash and the console will report an error

Image
3.All components except for Swiper in antd mobile can run normally

### System Info

```Shell
Both the built-in browser of Android 8 and Google Chrome will encounter errors
```

### PR DESCRIPTION
**Pull request by wre232114**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
fix #2103 

## Summary by CodeRabbit

- **Bug Fixes**
  - Resolved resource identifier conflicts to improve stability in large projects.
  - Enhanced compatibility between different module systems.

- **New Features**
  - Introduced improved build and runtime configurations, including browser compatibility and CSS processing.
  - Launched a sample React application with updated routing, internationalization, and mobile UI components.
  - Added new environment variables for development and production settings.
  - Introduced a new configuration file for managing build settings and plugins.
  - Added a new `.browserslistrc` file for specifying browser compatibility.
  - Introduced a new HTML entry point for the React application.
  - Enhanced the functionality of resource identifiers with new hash-based naming conventions.

- **Tests & Configurations**
  - Refined test cases and streamlined settings to support new resource management and build processes.
  - Introduced new configuration files for PostCSS and TypeScript.
  - Added a spell-check script to enhance code quality.

### CODE REVIEW

File: crates/compiler/src/update/regenerate_resources/generate_and_diff_resource_pots/test_handle_enforce_resource_pots.rs [hunk 1]
```diff
@@ -169,10 +166,7 @@ fn test_handle_enforce_resource_pots_one_module_changed() {
     )
     .unwrap();
   let mut module_group_graph = module_group_graph_from_entries(
-    &module_graph
-      .entries
-      .clone().into_keys()
-      .collect(),
+    &module_graph.entries.clone().into_keys().collect(),
```
Comment (fu050409) [inline crates/compiler/src/update/regenerate_resources/generate_and_diff_resource_pots/test_handle_enforce_resource_pots.rs:169]: Cosider use `module_graph.entries.keys().cloned().collect()` to avoid extra heap allocation?

Comment (wre232114) [reply crates/compiler/src/update/regenerate_resources/generate_and_diff_resource_pots/test_handle_enforce_resource_pots.rs:169]: This code is only for test, it's fine to clone over heap

**Review by fu050409 — APPROVED** [review]
