### PR TITLE
fix: Error in export field lookup algorithm

### LINKED ISSUE #494: [Bug] farm incorrect resolve dependency
### Steps to reproduce

1. cd example/solid
2.  add counter.tsx
```tsx
import { createSignal } from "solid-js";
import { customElement } from "solid-element";

customElement("my-counter", () => {
    const [count, setCount] = createSignal(0);
    return (
        <>
            <div>
                <button onClick={() => setCount(count() - 1)}>-</button>
                <span>{count()}</span>
                <button onClick={() => setCount(count() + 1)}>+</button>
            </div>
        </>
    );
});
```

3. change index.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <link rel="shortcut icon" type="image/ico" href="/src/assets/favicon.ico" />
    <title>Solid App</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root">
      <my-counter></my-counter>
    </div>

    <script src="./src/counter.tsx" type="module"></script>
  </body>
</html>
```

### What is expected?

import { createSignal } from "solid-js";

should resolve node_modules/solid-js/dist/solid.js

### What is actually happening?

resolve node_modules/solid-js/dist/server.js

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 74.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 9.1.2 - ~/.nvm/versions/node/v16.14.0/bin/npm
    pnpm: 8.6.2 - ~/.nvm/versions/node/v16.14.0/bin/pnpm
    Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.5.2
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by ErKeLost**
**Description:**

close #494 
**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

File: crates/plugin_resolve/src/resolver.rs [hunk 1]
```diff
@@ -946,4 +879,377 @@ impl Resolver {
...
+    config: &ConditionOptions,
+  ) -> Option<Vec<String>> {
+    if let Some(imports_field) =
+      self.get_field_value_from_package_json_info(package_json_info, "imports")
+    {
+      // TODO If the current package does not have a name, then look up for the name of the folder
+      let name = match self.get_field_value_from_package_json_info(package_json_info, "name") {
+        Some(n) => n,
+        None => {
+          // 如果 name 找不到 也要解析一下错误情况处理返回
```
Comment (wre232114) [inline crates/plugin_resolve/src/resolver.rs:941]: Change this comments to english

File: crates/plugin_resolve/src/resolver.rs [hunk 2]
```diff
@@ -946,4 +879,377 @@ impl Resolver {
...
+      }
+      Value::Array(values) => {
+        let arr_result = result.clone().unwrap_or_else(|| HashSet::new());
+        for item in values {
+          if let Some(item_result) = self.loop_value(item, keys, &mut Some(arr_result.clone())) {
+            return Some(item_result);
+          }
+        }
+
+        // 如果使用了初始化的结果集，返回结果
```
Comment (wre232114) [inline crates/plugin_resolve/src/resolver.rs:1102]: same here

File: crates/plugin_resolve/src/resolver.rs [hunk 3]
```diff
@@ -946,4 +879,377 @@ impl Resolver {
...
+        }
+      }
+
+      if let Some(longest_key) = longest {
+        m = mapping.get(&longest_key.to_string());
+      }
+    }
+    if m.is_none() {
+      self.throws(name, &entry, None);
+      return Vec::new(); // 返回一个空 Vec 作为错误处理的默认值
```
Comment (wre232114) [inline crates/plugin_resolve/src/resolver.rs:1240]: same here

File: crates/plugin_resolve/src/resolver.rs [hunk 4]
```diff
@@ -946,4 +879,377 @@ impl Resolver {
...
+    }
+    let v = self.loop_value(m.unwrap().clone(), &c, &mut None);
+    if v.is_none() {
+      self.throws(name, &entry, Some(1));
+      return Vec::new(); // 返回一个空 Vec 作为错误处理的默认值
```
Comment (wre232114) [inline crates/plugin_resolve/src/resolver.rs:1245]: same here

File: crates/core/src/config/mod.rs [hunk 5]
```diff
@@ -259,14 +261,7 @@ impl Default for ResolveConfig {
         String::from("html"),
         String::from("css"),
       ],
-      conditions: vec![
```
Comment (wre232114) [inline crates/core/src/config/mod.rs:262]: Why the default config  is removed
